# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
<<<<<<< Updated upstream
- script: echo Hello, world!
=======
- script: echo Hello, world this is another test after a second commit!
- script: echo Now will create stage deployments.
>>>>>>> Stashed changes
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
